
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jingyu
    username: root
    password: 123456
server:
  port: 8088
logging:
  level:
    root: info
## 微信小程序
wx:
  appSecret: 1234567892345678
  appId: wx7eb38d2488c598df
##阿里云配置
oss:
  endpoint: hjhjhjhjhj
  accessKeyId: hjhjhjhjhj
  accessKeySecret: hjhjhjhjhj
  bucketName: hjhjhjhjhj
